# Generated by Django 4.2.11 on 2024-03-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface_flows_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="frame",
            old_name="graph",
            new_name="flow",
        ),
        migrations.AlterField(
            model_name="frame",
            name="position_x",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="frame",
            name="position_y",
            field=models.FloatField(default=0),
        ),
    ]
