# Generated by Django 4.2.11 on 2024-03-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface_flows_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="flow_thumbnail_url",
            field=models.ImageField(default="flows//thumbnail.png", upload_to="flows/"),
        ),
    ]
