# Generated by Django 4.2.11 on 2024-03-30 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interface_flows_api", "0002_flow_flow_thumbnail_url"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "flow")},
        ),
    ]
