# Generated by Django 4.2.11 on 2024-05-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interface_flows_api", "0002_alter_flow_flow_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="process",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "Completed"),
                    ("FAIL", "Fail"),
                    ("IN_PROCESS", "In Process"),
                ],
                default="IN_PROCESS",
                max_length=20,
            ),
        ),
    ]
