# Generated by Django 4.2.11 on 2024-03-21 21:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interface_flows_api", "0003_flow_date_alter_flow_author"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("image_out", "image_in")},
        ),
    ]
