# Generated by Django 4.2.11 on 2024-03-21 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interface_flows_api", "0004_alter_connection_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="connection",
            old_name="image_in",
            new_name="frame_in",
        ),
        migrations.RenameField(
            model_name="connection",
            old_name="image_out",
            new_name="frame_out",
        ),
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("frame_out", "frame_in")},
        ),
    ]
