# Generated by Django 4.2.11 on 2024-03-22 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface_flows_api", "0005_rename_image_in_connection_frame_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frame",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frames",
                to="interface_flows_api.flow",
            ),
        ),
    ]
