# Generated by Django 4.2.11 on 2024-03-25 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface_flows_api", "0006_alter_frame_flow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_comment",
                to="interface_flows_api.profile",
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="frames_height",
            field=models.IntegerField(default=270),
        ),
        migrations.AddField(
            model_name="flow",
            name="frames_width",
            field=models.IntegerField(default=480),
        ),
        migrations.AddField(
            model_name="flow",
            name="status",
            field=models.CharField(
                choices=[("VR", "Verified"), ("MD", "On Moderation")],
                default="MD",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="visibility",
            field=models.CharField(
                choices=[("PB", "Public"), ("PV", "Private")],
                default="PB",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="flow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow_comment",
                to="interface_flows_api.flow",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=240),
        ),
        migrations.AlterField(
            model_name="frame",
            name="position_x",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="frame",
            name="position_y",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_like",
                to="interface_flows_api.profile",
            ),
        ),
    ]
