# Generated by Django 4.2.11 on 2024-03-25 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface_flows_api", "0007_remove_comment_user_comment_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frame",
            name="flow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frames",
                to="interface_flows_api.flow",
            ),
        ),
    ]
