# AWS
AWS_FOLDER_FRAMES = "frames/"
AWS_FOLDER_PROFILES = "profiles/"
AWS_FOLDER_THUMBNAILS = "flows/"
DEFAULT_PROFILE_PIC = "profile.png"
DEFAULT_FLOW_THUMBNAIL = "thumbnail.png"
# ML
MAX_TIME_BETWEEN_SCREENS = 100
